apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: pqm-core
    env: production
  name: pqm-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pqm-core
      env: production
  template:
    metadata:
      labels:
        app: pqm-core
        env: production
        role: rolling-update
    spec:
      containers:
      - image: bakcovn/pqm-core:latest
        imagePullPolicy: Always
        name: pqm-core
      imagePullSecrets:
      - name: regcred
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
